version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - volume_devops:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - network_devops

  backend:
    image: naynascimento/back_devops:1.0
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      DB_HOST: postgres
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    depends_on:
      - postgres
    networks:
      - network_devops

  frontend:
    image: naynascimento/front_devops:1.0
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - network_devops

volumes:
  volume_devops:

networks:
  network_devops:
    driver: bridge
